---
title: "Afternoon agenda: widgets and selected time series topics"
author: "Facilitator: Marcus W. Beck (USEPA ORD)"
date: "November 13, 2016, 1:00pm - 5:00pm"
output: 
  prettydoc::html_pretty:
    theme: cayman
    highlight: vignette
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The **afternoon session** will be an overview of the widgets of SWMPrats and selected time series topics.  The <a href="http://swmprats.net" target = "_parent">SWMPrats</a> website was created to assist the NERRS program with analysis and interpretation of SWMP data.  Three widgets on the website allow users to summarize trends within and between sites using a point-and-click approach.  Selected time series topics will include weighted regression for trend analysis, time series decomposition, and Seasonal Kendall tests.  

### Objectives

1) Understand the resources provided by SWMPrats
2) Learn the widgets and their assumptions
3) Familiarity with specific time series topics, why and how they are used

### 1:00pm Software set-up/help

Instructors will assist workshop attendees with **last‐minute** software issues.

### 1:15pm Introduction to Widgets

Overview of <a href="http://swmprats.net" target = "_parent">SWMPrats</a> website
Overview of interactive <a href="http://swmprats.net/swmp-widgets" target = "_parent">widgets</a>

* SWMP summary plots - evaluate trends of a single parameter at a single site  
* SWMP trend maps - compare trends of a single parameter within and between reserves using a map
* SWMP aggregations - compare aggregated trends of different parameters within and between reserves

Materials: <a href="https://fawda123.github.io/swmp_workshop_2016/training_modules/module1_widgets/widgets.pdf" target = "_parent">presentation</a>    

### 2:00pm Time Series Topic 1

Topic 1: Weighted regression in tidal waters

* Presentation on the theory and rationale of WRTDS for tidal waters
* Apply WRTDS to NERRS sites, assess model fit, create visualization of results
    
Materials: <a href="https://fawda123.github.io/swmp_workshop_2016/training_modules/module2_wrtds/wrtds.pdf" target = "_parent">presentation</a>, script

### 3:00pm BREAK

### 3:30pm Time Series Topic 2

Topic 2: Time series decomposition

* Presentation on the theory and rationale of time series decomposition
* Decompose NERRS time series using methods in SWMPr and other R packages
    
Materials: presentation, script

### 4:15pm Time Series Topic 3

Topic 3: Seasonal Kendall tests

* Presentation on the theory and rationale of Seasonal Kendall Tests
* Evaluate the significance and direction of a trend using NERRS data
    
Materials: presentation, script

### 5:00pm ADJOURN

